### ISSUE TITLE
Media query support

### ISSUE THREAD

**Issue by khacluan** [tungv/css-template#2]
Hi @tungv 
Thanks for very good package,

it could be use media query in css block of code ?

**Comment by tungv** [comment]
Hi @khacluan,
Thank you for taking time contributing to my package.
However, I don't think it's ever possible to do this with just inline css (which is the whole point of this package). But you might want to take a look at this https://github.com/contra/react-responsive. I've been using `react-responsive` together with `css-template` for a while. `react-responsive` gives you more power on what to render based on media-query, not just adding stylesheet rules to a class. I use it to render completely different component for mobile and desktop (add it works well with code splitting using `react-loadable` too)

If you really need media-query, and `:hover` and nested selector. I'd suggest to use emotion.sh or styled-jsx instead. They fully support "real css".

I'm going to close this. But if you can think of a way to implement it, feel free to reopen and submit a PR.

**Comment by khacluan** [comment]
@tungv thank you so much! :1st_place_medal:

**Comment by tungv** [comment]
btw, if you're interested in css-in-js discussions, feel free to join https://saigon.engineer group as well
